// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH35mjA30y0zE8jatiBXBr2MdeltBP-ow',
    appId: '1:272601085394:web:259671676496c68ed1c40b',
    messagingSenderId: '272601085394',
    projectId: 'application-job-eff9c',
    authDomain: 'application-job-eff9c.firebaseapp.com',
    storageBucket: 'application-job-eff9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv309odqBBViTA5qxBxD69KPw_caGYwdI',
    appId: '1:272601085394:android:1fccf4bb6a14c6d3d1c40b',
    messagingSenderId: '272601085394',
    projectId: 'application-job-eff9c',
    storageBucket: 'application-job-eff9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz3Mv5rpi-j7ysmb8LVGsdZMwJKLjH8bo',
    appId: '1:272601085394:ios:b159ccf0653a14e1d1c40b',
    messagingSenderId: '272601085394',
    projectId: 'application-job-eff9c',
    storageBucket: 'application-job-eff9c.appspot.com',
    iosClientId: '272601085394-t0gn0kvpnes91n8b5tva3hhtqvmc829q.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz3Mv5rpi-j7ysmb8LVGsdZMwJKLjH8bo',
    appId: '1:272601085394:ios:b159ccf0653a14e1d1c40b',
    messagingSenderId: '272601085394',
    projectId: 'application-job-eff9c',
    storageBucket: 'application-job-eff9c.appspot.com',
    iosClientId: '272601085394-t0gn0kvpnes91n8b5tva3hhtqvmc829q.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationJob',
  );
}
